# http://www.appveyor.com/docs/appveyor-yml

build: off
skip_tags: true

environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "7"
    - nodejs_version: "8"
    - nodejs_version: "9"

cache:
  - node_modules

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run dist
