environment:
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"
  TEST_SKIP_PRESETS: "sensitive, moderate"
install:
  - ps: Install-Product node $env:nodejs_version
  - yarn install
build: off
test_script:
  - node --version
  - npm --version
  - yarn --version
  - yarn run dist
