name: "GitHub Actions CI"
on: { push: { branches: [ master ] }, pull_request: { branches: [ master ] } }
jobs:
  lib:
    if: github.event_name == 'push'
    strategy: { matrix: { os: [ ubuntu-20.04, windows-2019, macos-10.15 ], node: [ 10, 12, 14, 15 ] }, fail-fast: false }
    runs-on: ${{ matrix.os }}
    steps:
      - { uses: actions/setup-node@v1, with: { node-version: "${{ matrix.node }}" } }
      - { uses: actions/checkout@v2 }
      - name: lib
        run: |
          node --version
          npm --version
          yarn --version
          npx envinfo
          yarn --pure-lockfile --network-timeout 60000
          yarn run lib
